// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XunitWebAPPMVCVSix.Models;

#nullable disable

namespace XunitWebAPPMVCVSix.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20220406053744_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("XunitWebAPPMVCVSix.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd372b99-806c-446b-b325-8813c292d4cc"),
                            AccountNumber = "4456622558855",
                            Age = 35,
                            Name = "Mosh"
                        },
                        new
                        {
                            Id = new Guid("5be02faa-34be-4055-acd8-ed52c3141bb0"),
                            AccountNumber = "7896622558855",
                            Age = 21,
                            Name = "Josh"
                        },
                        new
                        {
                            Id = new Guid("f761edb5-fe12-4d12-8dde-e6f1315d2508"),
                            AccountNumber = "4457788558855",
                            Age = 26,
                            Name = "James"
                        },
                        new
                        {
                            Id = new Guid("eb626d97-2d4d-4c9b-a531-6a742cd81b40"),
                            AccountNumber = "4456622554455",
                            Age = 31,
                            Name = "John"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
